
/*
============================================================
PHASE 6 - ANALYTICS REQUIREMENTS
SQL 6.5 - SALES DATE COVERAGE VALIDATION
============================================================

PURPOSE:
Validate the date coverage of sales orders.

VALIDATION:
- Identify the earliest and latest order dates.
- Count the total number of orders.
- Count orders by month.
- Identify months with no recorded orders within
  the available date range.

WHY THIS IS NEEDED:
Sales trend reporting requires a reliable date field
and an understanding of the period covered by the data.
This helps define the monthly reporting scope.

EXPECTED RESULT:
1. A summary showing the earliest and latest order dates.
2. A monthly breakdown showing order counts.

NOTE:
This is a read-only query. It does not modify data.
Months with no orders are not generated by this query;
the date range and observed months will be reviewed
before deciding how to handle missing months.
============================================================
*/

/*6.5.1*/
SELECT
    MIN(order_date) AS earliest_order_date,
    MAX(order_date) AS latest_order_date,
    COUNT(*) AS total_orders
FROM commerce.sales_order;

/*6.5.2*/
SELECT
    DATE_TRUNC('month', order_date)::date AS order_month,
    COUNT(*) AS order_count
FROM commerce.sales_order
GROUP BY DATE_TRUNC('month', order_date)
ORDER BY order_month;